=== ditrit/leto-modelizer-api/src/main/resources/library-schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "unevaluatedProperties": false,
  "type": "object",
  "required": ["name", "version", "description", "maintainer"],
  "properties": {
    "name": {
      "type": "string",
      "maxLength": 255
    },
    "version": {
      "type": "string",
      "maxLength": 255
    },
    "description": {
      "type": "string"
    },
    "maintainer": {
      "type": "string",
      "maxLength": 255
    },
    "icon": {
      "type": "string"
    },
    "templates": {
      "type": "array",
      "items": {
        "anyOf": [{
          "type": "object",
          "unevaluatedItems": false,
          "minItems": 1,
          "required": ["name", "type", "basePath", "plugins", "files"],
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 255
            },
            "type": {
              "enum": ["PROJECT"]
            },
            "description": {
              "type": "string"
            },
            "documentationUrl": {
              "type": "string"
            },
            "basePath": {
              "type": "string"
            },
            "icon": {
              "type": "string"
            },
            "plugins": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "unevaluatedItems": false,
              "minItems": 1
            },
            "schemas": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "unevaluatedItems": false
            },
            "files": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              },
              "unevaluatedItems": false,
              "minItems": 1
            }
          }
        }, {
          "type": "object",
          "unevaluatedItems": false,
          "minItems": 1,
          "required": ["name", "type", "basePath", "plugin", "files"],
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 255
            },
            "type": {
              "enum": ["DIAGRAM", "COMPONENT"]
            },
            "description": {
              "type": "string"
            },
            "documentationUrl": {
              "type": "string"
            },
            "basePath": {
              "type": "string"
            },
            "icon": {
              "type": "string"
            },
            "plugin": {
              "type": "string"
            },
            "schemas": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "unevaluatedItems": false
            },
            "files": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              },
              "unevaluatedItems": false,
              "minItems": 1
            }
          }
        }]
      }
    }
  }
}

=== ditrit/leto-modelizer-api/src/test/resources/libraries/valid/simple/index.json
{
  "name": "Simple library",
  "version": "0.1.0",
  "description": "Library with all templates types.",
  "maintainer": "Zorin95670",
  "icon": "icon.svg",
  "templates": [
    {
      "name": "Template of project 01",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 02",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 03",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 04",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 05",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 06",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 07",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 08",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 09",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of project 10",
      "type": "PROJECT",
      "description": "Project template example.",
      "documentationUrl": "doc url",
      "basePath": "",
      "plugins": ["@ditrit/terrator-plugin", "@ditrit/githubator-plugin"],
      "icon": "project.svg",
      "schemas": [
        ".github/workflows/schema.svg",
        "infra/schema.svg"
      ],
      "files": [
        ".github/workflows/CI.yml",
        "infra/main.tf"
      ]
    },
    {
      "name": "Template of diagram 1",
      "type": "DIAGRAM",
      "description": "Diagram template example.",
      "documentationUrl": "doc url",
      "basePath": ".github/workflows/",
      "plugin": "@ditrit/githubator-plugin",
      "icon": "diagram.svg",
      "schemas": ["schema.svg"],
      "files": ["CI.yml"]
    },
    {
      "name": "Template of diagram 2",
      "type": "DIAGRAM",
      "description": "Diagram template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "diagram.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf", "schema.svg"]
    },
    {
      "name": "Template of component 01",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 02",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 03",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 04",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 05",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 06",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 07",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 08",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 09",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 10",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 11",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 12",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 13",
      "type": "COMPONENT",
      "description": "Component template example.",
      "documentationUrl": "doc url",
      "basePath": "infra/",
      "plugin": "@ditrit/terrator-plugin",
      "icon": "component.svg",
      "schemas": ["schema.svg"],
      "files": ["main.tf"]
    },
    {
      "name": "Template of component 14",
      "type": "COMPONENT",
